name             'foltia'
maintainer       'Hiroyuki Nagata'
maintainer_email 'newserver002@gmail.com'
license          'All rights reserved'
description      'Installs/Configures foltia'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'cpan'
depends          'git'
depends          'apache2'
depends          'mercurial'
